name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm install

      - name: Compilation de l'EXE avec Electron Builder
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 1. Publie automatiquement l'EXE dans les Artifacts GitHub (Section bas de page de l'Action)
      - name: Sauvegarde de l'artifact EXE
        uses: actions/upload-artifact@v4
        with:
          name: Evox-Sender-Lite-Win
          path: dist/*.exe

      # 2. Publie / Mettre à jour une Release "Nightly / Latest" dans l'onglet Releases
      - name: Publication dans Releases GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Evox Sender Lite (Dernier Build)
          draft: false
          prerelease: false
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
